### PR TITLE
Fix #133: emit mouse events for drawn shapes

### LINKED ISSUE #133: `map_shape_click` not emitted when clicking on drawn shapes (v1, v0.2)
`map_shape_click` is not triggered in latest leaflet.extras for drawn shapes.

Tested in v1, v0.2

reprex:

```r
library(leaflet)
library(leaflet.extras)
library(shiny)

ui <- fluidPage(
  leafletOutput('map'),
  verbatimTextOutput('summary')
)

server <- function(input, output, session) {
  output$summary <- renderPrint({
    event <- input$map_shape_click
    print(event)
  })
  
  output$map <- renderLeaflet({
    leaflet() %>%
      addTiles() %>% 
      setView(10, 10, 4) %>% 
      addDrawToolbar(
        targetGroup = 'draw')
  })
}
shinyApp(ui, server)
```

Old bug with the same issue: https://github.com/rstudio/leaflet/issues/250

@byzheng perhaps you can explain how you solved this?

### PR DESCRIPTION
**Pull request by cmcaine**
Copy mouseHandler into draw_bindings and call it on draw.CREATE.

I release this contribution under the GPLv3 licence.

### CODE REVIEW

**Comment by cmcaine** [comment]
ref #133

**Comment by bhaskarvk** [comment]
I'll be resuming development of leaflet.extras in Dec and will tackle this in that round. Thanks!

**Comment by cmcaine** [comment]
Bump

**Comment by trafficonese** [comment]
Thank you. I included this in 7d8f028

**Pull request closed without merging**
