### PR TITLE
Added new WebGL Heatmap colour gradients

### PR DESCRIPTION
**Pull request by matthewgthomas**
Added five new colour gradients.

### CODE REVIEW

**Comment by schloerke** [comment]
@matthewgthomas 

I love the idea of more colors!  Any particular reason for these particular colors?

I'm wondering if we should add the 12 color spectrums from colorbrewer2.org. http://colorbrewer2.org/#type=sequential&scheme=YlOrRd&n=9

**Comment by bhaskarvk** [comment]
I have no objections. Do note that webgl heatmap is not as performant as the regular heatmap plugin and tends to slow down for large number of points. But I have no objections to adding more gradients.

**Comment by bhaskarvk** [comment]
I'll be resuming development of leaflet.extras in Dec and will tackle this in that round. Thanks!

**Comment by trafficonese** [comment]
12f0170 adds 12 new color-gradients from https://colorbrewer2.org

I also wrote this little script to easily create gradient images:
[/scripts/generate_color_gradients.R](https://github.com/trafficonese/leaflet.extras/blob/master/scripts/generate_color_gradients.R)

**Pull request closed without merging**
